version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.test
    command: ['bin/wait_for_db.sh', 'app', 'bin/run_container_test.sh']
    volumes:
      - .:/app
    links:
      - db
  db:
    image: postgres:12.1-alpine
    env_file: .env.test
    command: postgres -c 'fsync=off'
    logging:
      driver: none
    ports:
      - "5432:5432"
