FROM ruby:2.7.1-alpine

RUN apk add --no-cache --update build-base postgresql-dev tzdata dash postgresql-client

ENV RAILS_ENV development

WORKDIR /app

COPY Gemfile* ./

RUN bundle install

COPY . ./

CMD ["bundle", "exec", "rails", "server"]