apiVersion: batch/v1
kind: Job
metadata:
  name: app-db-migrate
spec:
  template:
    spec:
      containers:
        - name: app-migrate
          image: dtusk/just_cars
          command: [ "/usr/bin/dash" ]
          args:
            - "-c"
            - |
              set -ex

              bundle exec rails db:migrate
          envFrom:
            - configMapRef:
                name: app-configmap
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 600